= REACT - Effects, Reducers & Context

== Working with (Side) Effects
=== What is an _Effect_ (or a _*Side Effect*_)?
Main job of React: 
* Render UI & React to User Input
* Evaluate & Render JSX 
* Manage State & props
* React to (User) events & Input
* Re-evaluate Component upon State & Prop changes.

Side effects: Anything else, that doesn't matter to React
Store data in browser storage, Send HTTP requests to backend servers, set and manage timers.
These tasks *must happen outside of the normal component evaluation and render cycle*, especially since they might block/delay rendering (e.g. HTTP requests)
If such side effects are put incorrectly in the lifecycle of react component, it could create bugs, infinte loops or send too many requests.

=== Handling Side effects with the useEffect() hook.
Syntax:
*useEffect( () => { ... }, [ depedencies] );*

useEffect() hook recieves two parameters:
First:
A function that should be executed AFTER every component evaluation IF the specified dependencies changed.
Your side effect code goes into this function.

Second:
A list of dependencies, Dependencies of this effect - the function only runs if these dependencies changed.
Specify your dependencies of your function here.

useEffect() is to handle side effects, useEffect helps you to deal with code that should be executed in response to something.
(The component being loaded, the email address being updated) whenever you have and action that should be executed in response to some other action.

You must add all "things" you use in your effect function if those "things" could change because your component (or some parent component) re-rendered. That's why variables or state defined in component functions, props or functions defined in component functions have to be added as dependencies!


== Managing more complex state with Reducers
== Managing App-Wide or Component-Wide State with Context
