= REACT - Effects, Reducers & Context

== Managing more complex state with Reducers
Sometimes you have *more complex state* - for example if it got *multiple states, multiple ways of changing it or dependencies* to other states.

useState() then often *becomes hard or error-prone to use* - it's easy to write bad, inefficient or buggy code in such escenarios.

*useReducer()* can be used as a *replacement* for useState() if you need *more powerful state management*.

_Some uses cases when to use useReducer():_
When yuo have states that belong together.
If you have state updates that depends on other state.

=== Understanding useReducer()

*const [state, dispatchFn] = useReducer(reducerFn, initialState, initFn);*

useReducer() always returns an array with exactly two values.

state:
The state snapshot used in the component re-render/ re-evaluation cycle

dispatchFn:
A function that can be used to dispatch a new action(i.e. trigger an update of the state)

reducerFn:
(prevState, action) => newState
A function that is *triggered automatically* once an action is *dispatched* (via dispatchFn()) - it *receives the latest state snapshot* and should *return the new, updated state*

initialState:
The initial state

initFn:
A function to set the initial state programmatically

== Managing App-Wide or Component-Wide State with Context

