= REACT - Styling React components

== Conditional and dynamic styles
=== Inline Styles (Not the best approach)
When using INLINE STYLES, it has the higesth priority, so should be avoided as a best practice.
[source]
----
  <label style={{ color: !isValid ? 'red' : 'black' }}>Course Goal</label>
----

=== Setting CSS classes DYNAMICALLY
Backticks `` are requerid, it is a default Javascript feature called a template literal. 
Will  be treated as a regular string; a dynamic value ${} can be injected into that string.

[source]
----
  <div className={`form-control ${!isValid ? 'invalid' : ''}`}>
----

== Styled components
Regular CSS has global scope, so this could lead us to crashes, targeting elements with the same selector.
Two of the most popular approaches to avoid this problem are:
* Styled components (It's a package)
* 

=== Styled components
Class name are dynamically generated

[source]
----
const Button = Styled.button`
  font: inherit;
  padding: 0.5rem 1.5rem;
  border: 1px solid #8b005d;
  color: white;
  background: #8b005d;
  box-shadow: 0 0 4px rgba(0, 0, 0, 0.26);
  cursor: pointer;

&:focus {
  outline: none;
}

&:hover,
&:active {
  background: #ac0e77;
  border-color: #ac0e77;
  box-shadow: 0 0 8px rgba(0, 0, 0, 0.26);
}
`;
----

=== Dynamic props
Styled components forward all props you set on them to the underlying components
Now we are passing the property 'invalid' to the component:
_<FormControl invalid={!isValid}>_

This is contiditional CSS in the React component:
[source]
----
//Conditional className
  <FormControl className={!isValid && 'invalid'}>
----

*Dynamics props refers to conditional props(via js code) inside the CSS code in the styled component:*

[source]
----
From this_
& input {
  display: block;
  width: 100%;
  border: 1px solid #ccc;

To this:
& input {
  display: block;
  width: 100%;
  border: 1px solid ${props => invalid ? 'red' : '#ccc'};
----

=== Media queries
YOu just write the styles that should be applied if a the condition defined in the media querie is fullfiled

Inside the CSS code in the styled component: 
[source]
----
  @media (min-width: 768px) {
    width: auto;
  }
----

== CSS modules 
React supports CSS modules styling (https://create-react-app.dev/docs/adding-a-css-modules-stylesheet/)
[name].module.css file naming convention. CSS Modules allows the scoping of CSS by automatically creating a unique classname of the format [filename]\_[classname]\_\_[hash].

[source]
----
//The name of the css file must follow the convention: [name].module.css
import styles from './CourseInput.module.css';

//Using the CSS, you access the CSS selector with this syntax: _styles['form-control']_
 <div className={styles['form-control']}>


// USing CSS with conditions (Requires backsticks):
 <div className={`${styles['form-control']} ${!isValid && styles.invalid}`}>

----

*Using the CSS, you access the CSS selector with this syntax: _styles['form-control']*

*Using media queries in CSS modules:*
Just define the media query in the CSS module file:
[source]
----
@media (min-width: 768px) {
  .button {
    width: auto;
  }
----

and use it in the Component: _className={styles.button}_


