= REACT - Rendering Lists & Conditional Content.
=== Array.map()
Working with Dynamic Content
Outputting Dynamic Lists of Content
Rendering content under certain conditions.

Use {} to execute dynamic expressions in JSX code, you can execute Javascript expressions inside curly braces.

Iterating an array:
[source]
----
const Expenses = (values) => {  

  const [ filteredYear, setFilteredYear ] = useState('');

  const filterChangeHandler = (value) => {
    setFilteredYear(value);
  }

  // https://stackoverflow.com/questions/30803168/data-map-is-not-a-function
  
  return (
    <Card className="expenses">
      <ExpensesFilter selected={filteredYear} onChangeFilter={filterChangeHandler} />
      {values.items.map((item) => (
        <ExpenseItem
          key={item.id}
          title={item.title}
          amount={item.amount}
          date={item.date}
        />
      ))
      }
    </Card>
  );
}
----

=== key prop
Key is required for React to correctly identify and update (if needed) the list elements.
If is present on the component or HTML element, it can help React to identify individual items.
When ther is not a Key present, React render the new element as the last item in the list, and updates all items and replace their content
This is happening because to React all these items look similar, only sees that array changed, walk through all the items and updates the content inside of every item.

[source]
----
  let expensesContent = <p>No expenses Found.</p>

  if(filteredExpenses.length > 0) {
    expensesContent = filteredExpenses.map((item) => (
      <ExpenseItem
        key={item.id}
        title={item.title}
        amount={item.amount}
        date={item.date}
      />
    ));
  }
  
  return (
    <Card className="expenses">
      <ExpensesFilter selected={filteredYear} onChangeFilter={filterChangeHandler} />
      {expensesContent}
----

== Dynamic styling:

[source]
----
const ChartBar = props => {

  let barFillHeight = '0%';

  if (props.maxValue > 0) {
    barFillHeight = Math.round((props.value / props.maxValue) * 100) + '%';
  }

  return (
    <div className="chart-bar">
      <div className="chart-bar__inner">
        <div className="chart-bar__fill" style={{ height: barFillHeight }}></div>
----