= REACT - Learning and issues. Lesson-2

== Learned:
The component function(In React each component is a function) is not call a second time after the initial rendering just because a click occure or a variable changes DOES NOT TRIGGER THIS COMPONENT FUNCTION TO RUN AGAIN.

To tell React that it should run it again we should use the function from React: useState
*usesState allows to define values as state, where changes to those values should reflect in the component function being called again*

[source]
----
// Importing function useState() from React, as a named function ({namedFucntion})
import { useState } from 'react'
----

useState is a *React Hook*, all the Hooks must be called only inside of React component functions; they can Not be called outside of these functions. Neither can't be called inside nested functions, just directly inside such component function.

useState requires a DEFAULT VALUE, Ex. _useState(props.title)_
useState return an Array which the first element is the variable and the second element is a method to set the value of such variable.

We can use destructuring (feature of merdn JS) to store both elemnts from useState in separate variables:
const [title, setTitle] = useState(props.title);

When we call the setTitle function, will not only update the value of the variable titlle, will also execute the component function again. This tells React that the component should be re-evaluated.

useState registers some state for the component in which it is being called, It registers it for a specific component instance; per component instance basis

React knows that the init state was already assigned when executing the function component for the first time and will not initialize again when reevaluted the component, it will keep the latest value assigned.

React will re-evaluate the component when the state changes.